version: "1"
services:
  qpix-analysis:
    container_name: QpixAnalysis
    image: papahuhu/qpixana
    restart: on-failure
    environment:
      PORT: 8000
    volumes:
      - ./data:/home/data
      - ./source:/home/qpix
    ports:
      - '80:80'
    stdin_open: true
    tty: true